version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /ui
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /requirements
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: rust

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: dtolnay/rust-toolchain
