[application]
name = "bloom-ui"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Bloom - Edge AI Chat"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]

[web.resource.dev]
